# Data Preprocessing

- Feature Selection
- Data split

    - Train
    - Test
    - 2024 data (Tests)
    - 1968-2023 data (Full Open era)
    - 1990-2023 data (Modern Tennis era)

- Standardize features
- Dimensionality Reduction

In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, RobustScaler

In [2]:
df = pd.read_csv('../data/processed/3_engineered_data.csv', sep=';', encoding='utf-8')
df

,SURFACE,TOURNEY_DATE,TOURNEY_LEVEL,PLAYER_0_ID,PLAYER_0_HAND,PLAYER_0_HT,PLAYER_0_AGE,PLAYER_1_ID,PLAYER_1_HAND,PLAYER_1_HT,...,PERC_0_WIN_LAST_50,PERC_0_WIN_LAST_100,PERC_1_WIN_LAST_10,PERC_1_WIN_LAST_25,PERC_1_WIN_LAST_50,PERC_1_WIN_LAST_100,LAST_10_WIN_DIFF,LAST_25_WIN_DIFF,LAST_50_WIN_DIFF,LAST_100_WIN_DIFF
0,Clay,1967-12-28,A,100092,R,185.0,23.1,100035,R,185.0,...,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00
1,Clay,1967-12-28,A,100070,R,184.0,25.2,110991,R,185.0,...,0.00,0.00,0.0,0.00,0.00,0.00,-0.0,-0.00,-0.00,-0.00
2,Clay,1967-12-28,A,114613,U,184.0,21.2,100035,R,185.0,...,0.00,0.00,0.0,0.00,0.00,0.00,-0.0,-0.00,-0.00,-0.00
3,Clay,1967-12-28,A,110991,R,184.0,25.6,100092,R,185.0,...,1.00,1.00,0.0,0.00,0.00,0.00,-1.0,-1.00,-1.00,-1.00
4,Clay,1967-12-28,A,100051,R,184.0,27.1,100035,R,185.0,...,0.50,0.50,1.0,1.00,1.00,1.00,0.5,0.50,0.50,0.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375461,Hard,2024-12-18,F,210506,R,193.0,20.3,210460,R,180.0,...,0.46,0.49,0.5,0.50,0.50,0.50,0.1,-0.02,-0.04,-0.01
375462,Hard,2024-12-18,F,210506,R,193.0,20.3,209414,R,178.0,...,0.46,0.50,0.3,0.32,0.36,0.36,0.3,0.16,0.10,0.14
375463,Hard,2024-12-18,F,210150,R,193.0,19.2,210530,L,180.0,...,0.45,0.45,0.7,0.64,0.62,0.62,0.2,0.19,0.17,0.17
375464,Hard,2024-12-18,F,210460,R,180.0,19.6,209414,R,178.0,...,0.36,0.34,0.0,0.00,0.00,0.00,-0.3,-0.32,-0.36,-0.34
375465,Hard,2024-12-18,F,210150,R,193.0,19.2,209950,R,185.0,...,0.54,0.54,0.7,0.64,0.61,0.61,0.1,0.12,0.07,0.07

## Feature Selection

- Data analysis done in **data_visualization.ipynb**

In [3]:
df.columns

Index(['SURFACE', 'TOURNEY_DATE', 'TOURNEY_LEVEL', 'PLAYER_0_ID',
       'PLAYER_0_HAND', 'PLAYER_0_HT', 'PLAYER_0_AGE', 'PLAYER_1_ID',
       'PLAYER_1_HAND', 'PLAYER_1_HT', 'PLAYER_1_AGE', 'SCORE', 'BEST_OF',
       'AGE_DIFF', 'HT_DIFF', 'PLAYER_0_RATING', 'PLAYER_1_RATING',
       'RATING_DIFF', 'PLAYER_0_SURFACE_RATING', 'PLAYER_1_SURFACE_RATING',
       'SURFACE_RATING_DIFF', 'PERC_0_WIN_LAST_10', 'PERC_0_WIN_LAST_25',
       'PERC_0_WIN_LAST_50', 'PERC_0_WIN_LAST_100', 'PERC_1_WIN_LAST_10',
       'PERC_1_WIN_LAST_25', 'PERC_1_WIN_LAST_50', 'PERC_1_WIN_LAST_100',
       'LAST_10_WIN_DIFF', 'LAST_25_WIN_DIFF', 'LAST_50_WIN_DIFF',
       'LAST_100_WIN_DIFF'],
      dtype='object')

In [4]:
df = df.drop(df[['SURFACE', 'TOURNEY_LEVEL', 'PLAYER_0_ID',
       'PLAYER_0_HAND', 'PLAYER_0_HT', 'PLAYER_0_AGE', 'PLAYER_1_ID',
       'PLAYER_1_HAND', 'PLAYER_1_HT', 'PLAYER_1_AGE', 'BEST_OF']], axis=1)

In [5]:
df

,TOURNEY_DATE,SCORE,AGE_DIFF,HT_DIFF,PLAYER_0_RATING,PLAYER_1_RATING,RATING_DIFF,PLAYER_0_SURFACE_RATING,PLAYER_1_SURFACE_RATING,SURFACE_RATING_DIFF,...,PERC_0_WIN_LAST_50,PERC_0_WIN_LAST_100,PERC_1_WIN_LAST_10,PERC_1_WIN_LAST_25,PERC_1_WIN_LAST_50,PERC_1_WIN_LAST_100,LAST_10_WIN_DIFF,LAST_25_WIN_DIFF,LAST_50_WIN_DIFF,LAST_100_WIN_DIFF
0,1967-12-28,0,-5.5,-5.5,2000.000,2000.000,0.000,2000.000,2000.000,0.000,...,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00
1,1967-12-28,1,-0.4,-0.4,2000.000,1997.682,2.318,2000.000,1997.682,2.318,...,0.00,0.00,0.0,0.00,0.00,0.00,-0.0,-0.00,-0.00,-0.00
2,1967-12-28,1,-7.4,-7.4,2000.000,1996.842,3.158,2000.000,1996.842,3.158,...,0.00,0.00,0.0,0.00,0.00,0.00,-0.0,-0.00,-0.00,-0.00
3,1967-12-28,1,2.5,2.5,2000.000,2004.211,-4.211,2000.000,2004.211,-4.211,...,1.00,1.00,0.0,0.00,0.00,0.00,-1.0,-1.00,-1.00,-1.00
4,1967-12-28,1,-1.5,-1.5,2000.741,2001.024,-0.283,2000.741,2001.024,-0.283,...,0.50,0.50,1.0,1.00,1.00,1.00,0.5,0.50,0.50,0.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375461,2024-12-18,0,0.7,0.7,2172.068,2015.096,156.972,2129.714,2011.262,118.452,...,0.46,0.49,0.5,0.50,0.50,0.50,0.1,-0.02,-0.04,-0.01
375462,2024-12-18,0,-0.2,-0.2,2165.139,2100.983,64.156,2124.686,2059.176,65.510,...,0.46,0.50,0.3,0.32,0.36,0.36,0.3,0.16,0.10,0.14
375463,2024-12-18,1,0.2,0.2,2163.977,2051.259,112.718,2110.263,2033.247,77.016,...,0.45,0.45,0.7,0.64,0.62,0.62,0.2,0.19,0.17,0.17
375464,2024-12-18,1,-0.9,-0.9,2000.000,2098.214,-98.214,2000.000,2053.909,-53.909,...,0.36,0.34,0.0,0.00,0.00,0.00,-0.3,-0.32,-0.36,-0.34
375465,2024-12-18,1,-1.3,-1.3,2158.313,2178.170,-19.857,2106.507,2122.089,-15.582,...,0.54,0.54,0.7,0.64,0.61,0.61,0.1,0.12,0.07,0.07

In [6]:
df.describe()

,SCORE,AGE_DIFF,HT_DIFF,PLAYER_0_RATING,PLAYER_1_RATING,RATING_DIFF,PLAYER_0_SURFACE_RATING,PLAYER_1_SURFACE_RATING,SURFACE_RATING_DIFF,PERC_0_WIN_LAST_10,...,PERC_0_WIN_LAST_50,PERC_0_WIN_LAST_100,PERC_1_WIN_LAST_10,PERC_1_WIN_LAST_25,PERC_1_WIN_LAST_50,PERC_1_WIN_LAST_100,LAST_10_WIN_DIFF,LAST_25_WIN_DIFF,LAST_50_WIN_DIFF,LAST_100_WIN_DIFF
count,375466.000000,3.754660e+05,3.754660e+05,375466.000000,375466.000000,3.754660e+05,375466.000000,375466.000000,3.754660e+05,375466.000000,...,375466.000000,375466.000000,375466.000000,375466.000000,375466.000000,375466.000000,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05
mean,0.500000,8.989038e-19,8.989038e-19,2155.878052,2155.878052,-3.905973e-17,2086.075768,2086.075768,4.420714e-17,0.526473,...,0.540374,0.539536,0.446978,0.455909,0.458362,0.456130,-4.731072e-21,2.483813e-20,-1.005353e-19,1.005353e-19
std,0.500001,5.520826e+00,5.520826e+00,76.487966,76.487966,8.552164e+01,64.108162,64.108162,7.243444e+01,0.216344,...,0.174712,0.169038,0.220605,0.194398,0.185374,0.180101,2.959526e-01,2.535424e-01,2.376087e-01,2.283735e-01
min,0.000000,-4.170000e+01,-4.170000e+01,1918.139000,1918.139000,-3.902680e+02,1942.864000,1942.864000,-3.548380e+02,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00
25%,0.000000,-3.600000e+00,-3.600000e+00,2112.510500,2112.510500,-5.229000e+01,2028.802250,2028.802250,-4.617700e+01,0.400000,...,0.440000,0.450000,0.300000,0.360000,0.380000,0.380000,-2.000000e-01,-1.600000e-01,-1.400000e-01,-1.300000e-01
50%,0.500000,0.000000e+00,0.000000e+00,2167.829500,2167.829500,0.000000e+00,2085.299000,2085.299000,0.000000e+00,0.500000,...,0.540000,0.530000,0.500000,0.480000,0.480000,0.470000,0.000000e+00,0.000000e+00,0.000000e+00,-0.000000e+00
75%,1.000000,3.600000e+00,3.600000e+00,2208.603750,2208.603750,5.229000e+01,2132.397750,2132.397750,4.617700e+01,0.700000,...,0.660000,0.650000,0.600000,0.570000,0.570000,0.560000,2.000000e-01,1.600000e-01,1.400000e-01,1.300000e-01
max,1.000000,4.170000e+01,4.170000e+01,2427.004000,2427.004000,3.902680e+02,2373.133000,2373.133000,3.548380e+02,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

## Data Split

In [7]:
feature = df.drop('SCORE', axis=1)
feature.head(3)

,TOURNEY_DATE,AGE_DIFF,HT_DIFF,PLAYER_0_RATING,PLAYER_1_RATING,RATING_DIFF,PLAYER_0_SURFACE_RATING,PLAYER_1_SURFACE_RATING,SURFACE_RATING_DIFF,PERC_0_WIN_LAST_10,...,PERC_0_WIN_LAST_50,PERC_0_WIN_LAST_100,PERC_1_WIN_LAST_10,PERC_1_WIN_LAST_25,PERC_1_WIN_LAST_50,PERC_1_WIN_LAST_100,LAST_10_WIN_DIFF,LAST_25_WIN_DIFF,LAST_50_WIN_DIFF,LAST_100_WIN_DIFF
0,1967-12-28,-5.5,-5.5,2000.0,2000.000,0.000,2000.0,2000.000,0.000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1967-12-28,-0.4,-0.4,2000.0,1997.682,2.318,2000.0,1997.682,2.318,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,-0.0,-0.0,-0.0
2,1967-12-28,-7.4,-7.4,2000.0,1996.842,3.158,2000.0,1996.842,3.158,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,-0.0,-0.0,-0.0

In [8]:
target = df[['SCORE']]
target.value_counts()

SCORE
0        187733
1        187733
Name: count, dtype: int64

In [9]:
feature.to_csv('../data/processed/5.1_data_feature.csv', sep=';', encoding='utf-8', index=False)
target.to_csv('../data/processed/5.1_data_target.csv', sep=';', encoding='utf-8', index=False)

## Standardize Features

#### StandardScaler (mean = 0, std = 1)

In [10]:
scaler = StandardScaler()

In [11]:
feature_std_esc = scaler.fit_transform(feature.loc[:, feature.columns != 'TOURNEY_DATE'])
feature_std_esc = pd.DataFrame(feature_std_esc)

In [12]:
feature_std_esc['TOURNEY_DATE'] = feature['TOURNEY_DATE']
feature_std_esc.head(3)

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,TOURNEY_DATE
0,-0.996229,-0.996229,-2.037945,-2.037945,4.567240e-19,-1.342667,-1.342667,-6.103064e-19,-2.433507,-2.884624,...,-3.191816,-2.026146,-2.345243,-2.472635,-2.532638,1.598593e-20,-9.796454e-20,4.231134e-19,-4.402236e-19,1967-12-28
1,-0.072453,-0.072453,-2.037945,-2.068250,2.710429e-02,-1.342667,-1.378824,3.200140e-02,-2.433507,-2.884624,...,-3.191816,-2.026146,-2.345243,-2.472635,-2.532638,1.598593e-20,-9.796454e-20,4.231134e-19,-4.402236e-19,1967-12-28
2,-1.340381,-1.340381,-2.037945,-2.079232,3.692637e-02,-1.342667,-1.391927,4.359810e-02,-2.433507,-2.884624,...,-3.191816,-2.026146,-2.345243,-2.472635,-2.532638,1.598593e-20,-9.796454e-20,4.231134e-19,-4.402236e-19,1967-12-28

In [13]:
feature_std_esc.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
count,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05
mean,-1.277390e-19,-1.277390e-19,3.410611e-15,-2.538580e-15,2.507468e-19,4.369846e-15,4.350467e-15,4.257965e-20,-3.512348e-16,6.758242e-16,1.356493e-16,5.886211e-16,-1.090039e-16,2.252747e-16,-1.114262e-16,-3.512348e-16,6.339637e-19,5.582665e-19,-2.744022e-19,-1.040836e-19
std,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00
min,-7.553228e+00,-7.553228e+00,-3.108193e+00,-3.108193e+00,-4.563389e+00,-2.233911e+00,-2.233911e+00,-4.898754e+00,-2.433507e+00,-2.884624e+00,-3.092944e+00,-3.191816e+00,-2.026146e+00,-2.345243e+00,-2.472635e+00,-2.532638e+00,-3.378924e+00,-3.944119e+00,-4.208606e+00,-4.378797e+00
25%,-6.520772e-01,-6.520772e-01,-5.669860e-01,-5.669860e-01,-6.114250e-01,-8.933901e-01,-8.933901e-01,-6.375015e-01,-5.845952e-01,-6.238505e-01,-5.745138e-01,-5.296834e-01,-6.662498e-01,-4.933655e-01,-4.227219e-01,-4.227083e-01,-6.757848e-01,-6.310590e-01,-5.892049e-01,-5.692436e-01
50%,-1.628207e-19,-1.628207e-19,1.562529e-01,1.562529e-01,4.567240e-19,-1.211654e-02,-1.211654e-02,-6.103064e-19,-1.223672e-01,-8.557110e-02,-2.143344e-03,-5.641538e-02,2.403476e-01,1.239270e-01,1.167291e-01,7.701194e-02,1.598593e-20,-9.796454e-20,4.231134e-19,-4.402236e-19
75%,6.520772e-01,6.520772e-01,6.893342e-01,6.893342e-01,6.114250e-01,7.225608e-01,7.225608e-01,6.375015e-01,8.020887e-01,7.218481e-01,6.847013e-01,6.534867e-01,6.936463e-01,5.868963e-01,6.022349e-01,5.767321e-01,6.757848e-01,6.310590e-01,5.892049e-01,5.692436e-01
max,7.553228e+00,7.553228e+00,3.544692e+00,3.544692e+00,4.563389e+00,4.477708e+00,4.477708e+00,4.898754e+00,2.188773e+00,2.498170e+00,2.630761e+00,2.724034e+00,2.506841e+00,2.798861e+00,2.921874e+00,3.019809e+00,3.378924e+00,3.944119e+00,4.208606e+00,4.378797e+00

#### RobustScaler (better with outliers)

In [14]:
robust = RobustScaler()

In [15]:
feature_robust_esc = robust.fit_transform(feature.loc[:, feature.columns != 'TOURNEY_DATE'])
feature_robust_esc = pd.DataFrame(feature_robust_esc)

In [16]:
feature_robust_esc['TOURNEY_DATE'] = feature['TOURNEY_DATE']
feature_robust_esc.head(3)

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,TOURNEY_DATE
0,-0.763889,-0.763889,-1.746527,-1.746527,0.000000,-0.823385,-0.823385,0.000000,-1.666667,-2.08,...,-2.65,-1.666667,-2.285714,-2.526316,-2.611111,0.0,0.0,0.0,0.0,1967-12-28
1,-0.055556,-0.055556,-1.746527,-1.770650,0.022165,-0.823385,-0.845761,0.025099,-1.666667,-2.08,...,-2.65,-1.666667,-2.285714,-2.526316,-2.611111,-0.0,-0.0,-0.0,-0.0,1967-12-28
2,-1.027778,-1.027778,-1.746527,-1.779391,0.030197,-0.823385,-0.853869,0.034195,-1.666667,-2.08,...,-2.65,-1.666667,-2.285714,-2.526316,-2.611111,-0.0,-0.0,-0.0,-0.0,1967-12-28

In [17]:
feature_robust_esc.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
count,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05,375466.000000,375466.000000,3.754660e+05,375466.000000,375466.000000,375466.000000,375466.000000,375466.000000,375466.000000,375466.000000,375466.000000,3.754660e+05,3.754660e+05,3.754660e+05,3.754660e+05
mean,9.462145e-20,9.462145e-20,-1.243734e-01,-1.243734e-01,2.081672e-19,0.007498,0.007498,4.636451e-19,0.088244,0.063589,0.001702,0.047682,-0.176740,-0.114719,-0.113887,-0.077055,-1.608565e-19,4.731072e-21,-1.182768e-21,3.713892e-19
std,7.667814e-01,7.667814e-01,7.959765e-01,7.959765e-01,8.177629e-01,0.618832,0.618832,7.843129e-01,0.721146,0.743109,0.794147,0.845188,0.735351,0.925703,0.975652,1.000561,7.398815e-01,7.923199e-01,8.486024e-01,8.783598e-01
min,-5.791667e+00,-5.791667e+00,-2.598419e+00,-2.598419e+00,-3.731765e+00,-1.374915,-1.374915,-3.842151e+00,-1.666667,-2.080000,-2.454545,-2.650000,-1.666667,-2.285714,-2.526316,-2.611111,-2.500000e+00,-3.125000e+00,-3.571429e+00,-3.846154e+00
25%,-5.000000e-01,-5.000000e-01,-5.756804e-01,-5.756804e-01,-5.000000e-01,-0.545359,-0.545359,-5.000000e-01,-0.333333,-0.400000,-0.454545,-0.400000,-0.666667,-0.571429,-0.526316,-0.500000,-5.000000e-01,-5.000000e-01,-5.000000e-01,-5.000000e-01
50%,0.000000e+00,0.000000e+00,2.366176e-15,2.366176e-15,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,-0.000000e+00
75%,5.000000e-01,5.000000e-01,4.243196e-01,4.243196e-01,5.000000e-01,0.454641,0.454641,5.000000e-01,0.666667,0.600000,0.545455,0.600000,0.333333,0.428571,0.473684,0.500000,5.000000e-01,5.000000e-01,5.000000e-01,5.000000e-01
max,5.791667e+00,5.791667e+00,2.697115e+00,2.697115e+00,3.731765e+00,2.778441,2.778441,3.842151e+00,1.666667,1.920000,2.090909,2.350000,1.666667,2.476190,2.736842,2.944444,2.500000e+00,3.125000e+00,3.571429e+00,3.846154e+00

In [18]:
feature_std_esc.to_csv('../data/processed/5.2_data_feature_std_esc.csv', sep=';', encoding='utf-8', index=False)
feature_robust_esc.to_csv('../data/processed/5.2_data_feature_robust_esc.csv', sep=';', encoding='utf-8', index=False)

## Dimensionality Reduction